/**
 * Top-level entry for @chaoxu/coflat/reader.
 *
 * The implementation lives in src/reader/reader.ts. This shim exists to keep
 * the Vite build entry stable and the package's `./reader` sub-path export
 * pointing at a top-level file.
 */

export type { CoflatThemeManifest, CoflatThemeTarget } from "./src/core/theme-manifest";
export {
  applyReaderSourceDecorations,
  applySourceRangeAttrs,
  type BlockCounterEntry,
  blueprintBookThemeManifest,
  COFLAT_READER_CLASS,
  COFLAT_READER_DOCUMENT_CLASS,
  COFLAT_READER_SHELL_CLASS,
  COFLAT_READER_TOC_CLASS,
  COFLAT_THEME_SCOPE_CLASS,
  type ConditionalWriteResult,
  closestMathSourceCarrier,
  closestSourceRangeCarrier,
  createReaderCitationClusterPreviewBody,
  type DocumentContext,
  type ElementSourceRangeOptions,
  type FileEntry,
  type FileSystem,
  type HydrateMathOptions,
  type HydrateReferencesOptions,
  hydrateBlockDisclosures,
  hydrateMath,
  hydrateMedia,
  hydrateReaderDisclosures,
  hydrateReaderHoverPreviews,
  hydrateReferences,
  isSourceRangeCarrier,
  type LinkResolver,
  mapDomNodeToSource,
  mapDomPointToSource,
  mapDomRangeToSource,
  type ParseSourceRangeOptions,
  parseSourceOffset,
  type ReaderHoverPreviewEnv,
  type ReaderHoverPreviewOptions,
  type ReaderHtmlResult,
  type ReaderLayoutGap,
  type ReaderOutlineEntry,
  type ReaderReferencePreviewEntry,
  type ReaderReferencePreviewIndex,
  type ReaderSourceDecoration,
  type RefResolver,
  type RenderedSourceAnchor,
  type RenderedSourceAnchorGranularity,
  type RenderedSourceAnchorLookupOptions,
  type RenderOptions,
  renderedAnchorsForSourceLineRange,
  renderedAnchorsForSourceRange,
  renderedSourceAnchorsFromDom,
  renderToHtml,
  renderToText,
  type SourceLineRange,
  type SourcePosition,
  type SourcePositionScrollOptions,
  type SourceRange,
  type SourceRangeAttrsOptions,
  type SourceRangeCarrierOptions,
  scrollReaderToSourcePosition,
  sourceElementAtPosition,
  sourceLineRangeFromElement,
  sourceRangeAttrs,
  sourceRangeFromDataset,
  sourceRangeFromElement,
  sourceRangeFromValues,
  type TruncatedInfo,
  type VisibleSourcePositionOptions,
  visibleSourcePositionInScroller,
} from "./src/reader/reader";
