/**
 * Top-level entry for @chaoxu/coflat/reader.
 *
 * The implementation lives in src/reader/reader.ts. This shim exists to keep
 * the Vite build entry stable and the package's `./reader` sub-path export
 * pointing at a top-level file.
 */
export {
  COFLAT_READER_CLASS,
  COFLAT_READER_DOCUMENT_CLASS,
  COFLAT_READER_SHELL_CLASS,
  COFLAT_READER_TOC_CLASS,
  COFLAT_THEME_SCOPE_CLASS,
  blueprintBookThemeManifest,
  renderToHtml,
  renderToText,
  applySourceRangeAttrs,
  applyReaderSourceDecorations,
  closestMathSourceCarrier,
  closestSourceRangeCarrier,
  isSourceRangeCarrier,
  mapDomRangeToSource,
  mapDomNodeToSource,
  mapDomPointToSource,
  parseSourceOffset,
  renderedAnchorsForSourceLineRange,
  renderedAnchorsForSourceRange,
  renderedSourceAnchorsFromDom,
  scrollReaderToSourcePosition,
  sourceLineRangeFromElement,
  sourceRangeAttrs,
  sourceElementAtPosition,
  sourceRangeFromDataset,
  sourceRangeFromElement,
  sourceRangeFromValues,
  visibleSourcePositionInScroller,
  hydrateBlockDisclosures,
  hydrateMedia,
  hydrateReaderDisclosures,
  hydrateMath,
  createReaderCitationClusterPreviewBody,
  hydrateReaderHoverPreviews,
  hydrateReferences,
  type HydrateMathOptions,
  type HydrateReferencesOptions,
  type ReaderHtmlResult,
  type ReaderLayoutGap,
  type ReaderOutlineEntry,
  type RenderOptions,
  type ReaderReferencePreviewEntry,
  type ReaderReferencePreviewIndex,
  type ReaderHoverPreviewEnv,
  type ReaderHoverPreviewOptions,
  type ElementSourceRangeOptions,
  type ParseSourceRangeOptions,
  type ReaderSourceDecoration,
  type RenderedSourceAnchor,
  type RenderedSourceAnchorGranularity,
  type RenderedSourceAnchorLookupOptions,
  type SourceLineRange,
  type SourcePosition,
  type SourcePositionScrollOptions,
  type SourceRange,
  type SourceRangeAttrsOptions,
  type SourceRangeCarrierOptions,
  type VisibleSourcePositionOptions,
  type TruncatedInfo,
  type BlockCounterEntry,
  type ConditionalWriteResult,
  type DocumentContext,
  type FileEntry,
  type FileSystem,
  type LinkResolver,
  type RefResolver,
} from "./src/reader/reader";
export type { CoflatThemeManifest, CoflatThemeTarget } from "./src/core/theme-manifest";
