import "../../../src/editor/editor-theme.css";
import "../../../src/themes/blueprint-book.css";
import { hydrateBlockDisclosures, renderToHtml } from "../../../reader";

const root = document.getElementById("theme-root");
if (!(root instanceof HTMLElement)) {
  throw new Error("missing #theme-root");
}

const source = `# Blueprint Document

This page mirrors the structure generated by Lean Blueprint: a document title,
left table of contents, theorem environments, proofs, and display math.

## Main Result

::: {.definition #def-theme title="Scoped theme"}
A blueprint theme is applied by the host on the nearest scoped root.
:::

::: {.theorem #main-result title="Readable column"}
Every optimal document theme has a readable column and stable theorem rails.
:::

::: {.proof title="the readable column theorem"}
The host applies a scoped class, and Coflat surfaces inherit variables from it.

$$
\\operatorname{width}(D) \\le 75\\operatorname{ch}
$$
:::
`;

const { html } = renderToHtml(source);

root.innerHTML = `
  <div class="cf-theme-scope cf-theme-blueprint-book cf-reader-shell" data-cf-theme="blueprint-book">
    <header class="cf-reader-header">
      <h1 class="cf-reader-header-title">Blueprint Document</h1>
    </header>
    <aside class="cf-reader-toc" aria-label="Document outline">
      <a href="#def-theme">Definition</a>
      <a href="#main-result" aria-current="page">Main Result</a>
    </aside>
    <main class="cf-reader-document">
      <div class="cf-doc-surface cf-doc-flow cf-reader">${html}</div>
    </main>
  </div>
`;

const reader = root.querySelector<HTMLElement>(".cf-reader");
if (reader) hydrateBlockDisclosures(reader);
